// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9NUZe01mHfCfj1fUYOoHncsXGc1p94mg',
    appId: '1:349054114743:android:85901551077568ae23a632',
    messagingSenderId: '349054114743',
    projectId: 'binaytech-13dc8',
    storageBucket: 'binaytech-13dc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA45vrTC767bCIIyXeNfGkDvd49V1MPoXg',
    appId: '1:349054114743:ios:e22bd7e1c0024e5a23a632',
    messagingSenderId: '349054114743',
    projectId: 'binaytech-13dc8',
    storageBucket: 'binaytech-13dc8.firebasestorage.app',
    iosBundleId: 'com.binaytech.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA45vrTC767bCIIyXeNfGkDvd49V1MPoXg',
    appId: '1:349054114743:ios:e22bd7e1c0024e5a23a632',
    messagingSenderId: '349054114743',
    projectId: 'binaytech-13dc8',
    storageBucket: 'binaytech-13dc8.firebasestorage.app',
    iosBundleId: 'com.binaytech.app',
  );
}
